### PR TITLE
Add other Go versions to be tested

### PR DESCRIPTION
**Pull request by areski**

### CODE REVIEW

**Comment by areski** [comment]
the tests on travis-ci seems to be failing for some strange reasons. any idea?

**Comment by MJDSys** [comment]
With regards to go 1.1, it looks like Google's protobuf library dropped support for it.  Thus we should probably drop support for it in goriakpbc (@tpjg, thoughts?).

Regarding the other versions, I'd guess that is a transient error caused by Riak then a bug in the code.  Adding sleep statements may help Riak catch up, but that is less then ideal.  I re-ran those jobs, and 1.4 now compiles fine, so that supports my theory.

**Comment by tpjg** [comment]
@MJDSys , as usual I agree with you. Since only the go 1.1 test is failing and we definitely don't want to maintain a fork of Google's protobuf I think we should drop support for it.

@areski , can you please update your patch to remove go 1.1?

**Comment by areski** [comment]
@tpjg Done

**Comment by tpjg** [comment]
Hm, interesting. Now also the tests for 1.2 and 1.3 are failing (for the SearchTest only). I'll need to check what's wrong.

**Comment by areski** [comment]
@tpjg it seems that it's 1.3 & 1.4 that are failing, and this won't make much sense as 'tip' is the same as 1.4.  Maybe it's related to previous comment from @MJDSys on the "transient error"

**Comment by tpjg** [comment]
Sorry, yes 1.3&1.4. It's probably more a race condition or something else otherwise unrelated to Go versions. I'll need to check the "search_test.go" function, probably print the err before the assert in line 40 to see what's happening.

**Comment by tpjg** [comment]
Of course on my dev machine (Go 1.4, riak 1.4.8, OS X) all tests are passing. I'll have to create a branch. Looking at the comments in search_test.go past line 40 it seems the tests for Search are currently not functioning anyway. @MJDSys what do you think? Just skip these tests?

**Comment by MJDSys** [comment]
I just tried the tests on a clean VM using Basho's official builds for 1.4.12.  Its not failing no matter how much I run the tests.  I wonder if there is a bug in Travis's setup, as the test did fail if Riak has search disabled.  I think before test tests are disabled, the cause should be investigated.
Regardless, this PR isn't causing the issue, so I'll merge it (Especially since the tests have turned green).  I'll open an issue after to track this.

**Pull request merged**
